name: reactive_ble
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_reactive_ble: ^2.7.3
  permission_handler: ^5.1.0+2
  rxdart: ^0.26.0
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  freezed: ^0.12.7

flutter:
  uses-material-design: true
